baseURL = 'https://astropi-hackathon.org/'
languageCode = 'en-US'
title = 'AstroPi Hackathon'
uglyURLs = "false"
enableEmoji = "true"
[params]
    description = "Oficiální stránky AstroPi Hackathonu"
[markup.goldmark.renderer]
    unsafe = "true"
[menus]
    [[menu.main]]
        identifier = "domu"
        name = "Domů"
        url = "/"
        weight = "1"
    [[menu.main]]
        identifier = "aktualni-rocnik"
        name = "Aktuální ročník"
        url = "/aktualni-rocnik"
        weight = "2"
    [[menu.main]]
        identifier = "minule-rocniky"
        name = "Minulé ročníky"
        url = "/minule-rocniky"
        weight = "3"
    [[menu.main]]
        identifier = "astropi"
        name = "AstroPi"
        url = "/astropi"
        weight = "4"
    [[menu.main]]
        identifier = "kontakt"
        name = "Kontakt"
        url = "/kontakt"
        weight = "5"
    [[menu.past]]
        identifier = "praha22"
        name = "Praha 2022"
        url = "/minule-rocniky/praha22"
        weight = "99"
    [[menu.past]]
        identifier = "brno22"
        name = "Brno 2022"
        url = "/minule-rocniky/brno22"
        weight = "98"
    [[menu.past]]
        identifier = "brno23"
        name = "Brno 2023"
        url = "/minule-rocniky/brno23"
        weight = "97"
    [[menu.past]]
        identifier = "ostrava23"
        name = "Ostrava 2023"
        url = "/minule-rocniky/ostrava23"
        weight = "96"